// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mindflow_backend.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace Mindflow_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924232750_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Mindflow_backend.AiFeedback.Domain.Model.Entities.AiFeedbackRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("comment");

                    b.Property<int>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("content_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_ai_feedback_ratings");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_ai_feedback_ratings_user_id");

                    b.HasIndex("UserId", "ContentId", "ContentType")
                        .IsUnique()
                        .HasDatabaseName("i_x_ai_feedback_ratings_user_id_content_id_content_type");

                    b.ToTable("ai_feedback_ratings");
                });

            modelBuilder.Entity("Mindflow_backend.AiIntegration.Domain.Model.Entities.AiMetricLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("error_message");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("int")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("operation");

                    b.Property<int>("PromptLength")
                        .HasColumnType("int")
                        .HasColumnName("prompt_length");

                    b.Property<int>("ResponseLength")
                        .HasColumnType("int")
                        .HasColumnName("response_length");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("success");

                    b.HasKey("Id")
                        .HasName("p_k_ai_metric_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("i_x_ai_metric_logs_created_at");

                    b.ToTable("ai_metric_logs");
                });

            modelBuilder.Entity("Mindflow_backend.Chat.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("content");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_chat_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("i_x_chat_messages_conversation_id");

                    b.ToTable("chat_messages");
                });

            modelBuilder.Entity("Mindflow_backend.Chat.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_conversations");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_conversations_user_id");

                    b.ToTable("conversations");
                });

            modelBuilder.Entity("Mindflow_backend.Habits.Domain.Model.Aggregates.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("frequency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<bool>("PausedByAi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("paused_by_ai");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("Streak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("streak");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_habits");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_habits_user_id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("i_x_habits_user_id_status");

                    b.ToTable("habits");
                });

            modelBuilder.Entity("Mindflow_backend.Habits.Domain.Model.Entities.CachedHabitSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("generated_at");

                    b.Property<string>("SuggestionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("suggestions_json");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_cached_habit_suggestions");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_cached_habit_suggestions_user_id");

                    b.ToTable("cached_habit_suggestions");
                });

            modelBuilder.Entity("Mindflow_backend.Habits.Domain.Model.Entities.HabitCompletionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("completed");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int>("HabitId")
                        .HasColumnType("int")
                        .HasColumnName("habit_id");

                    b.Property<string>("HabitName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("habit_name");

                    b.HasKey("Id")
                        .HasName("p_k_habit_completion_logs");

                    b.HasIndex("Date")
                        .HasDatabaseName("i_x_habit_completion_logs_date");

                    b.HasIndex("HabitId")
                        .HasDatabaseName("i_x_habit_completion_logs_habit_id");

                    b.HasIndex("HabitId", "Date")
                        .HasDatabaseName("i_x_habit_completion_logs_habit_id_date");

                    b.ToTable("habit_completion_logs");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.EntryTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("EntryId")
                        .HasColumnType("int")
                        .HasColumnName("entry_id");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("tag_id");

                    b.HasKey("Id")
                        .HasName("p_k_entry_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("i_x_entry_tags_tag_id");

                    b.HasIndex("EntryId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("i_x_entry_tags_entry_id_tag_id");

                    b.ToTable("entry_tags");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AiResponse")
                        .HasColumnType("TEXT")
                        .HasColumnName("ai_response");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<string>("ClientId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("client_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("LONGTEXT")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("HasPreview")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_preview");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sentiment");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_journal_entries");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_journal_entries_user_id");

                    b.HasIndex("UserId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("i_x_journal_entries_user_id_client_id");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("i_x_journal_entries_user_id_date");

                    b.ToTable("journal_entries");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.JournalSearchToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("EntryId")
                        .HasColumnType("int")
                        .HasColumnName("entry_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_journal_search_tokens");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("i_x_journal_search_tokens_entry_id");

                    b.HasIndex("UserId", "TokenHash")
                        .HasDatabaseName("i_x_journal_search_tokens_user_id_token_hash");

                    b.ToTable("journal_search_tokens");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("EntryId")
                        .HasColumnType("int")
                        .HasColumnName("entry_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("p_k_media");

                    b.HasIndex("EntryId")
                        .HasDatabaseName("i_x_media_entry_id");

                    b.ToTable("media");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_tags");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("Mindflow_backend.WellnessContent.Domain.Entities.WellnessExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("audio_url");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int?>("Cycles")
                        .HasColumnType("int")
                        .HasColumnName("cycles");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_seconds");

                    b.Property<int?>("ExhaleSeconds")
                        .HasColumnType("int")
                        .HasColumnName("exhale_seconds");

                    b.Property<int?>("HoldAfterExhaleSeconds")
                        .HasColumnType("int")
                        .HasColumnName("hold_after_exhale_seconds");

                    b.Property<int?>("HoldSeconds")
                        .HasColumnType("int")
                        .HasColumnName("hold_seconds");

                    b.Property<int?>("InhaleSeconds")
                        .HasColumnType("int")
                        .HasColumnName("inhale_seconds");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_wellness_exercises");

                    b.HasIndex("Type", "IsActive")
                        .HasDatabaseName("i_x_wellness_exercises_type_is_active");

                    b.ToTable("wellness_exercises");
                });

            modelBuilder.Entity("Mindflow_backend.iam.domain.model.aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("google_id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("occupation");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PinHash")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pin_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("User")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_google_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Mindflow_backend.iam.domain.model.entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token");

                    b.Property<bool>("Used")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("used");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_password_reset_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("i_x_password_reset_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens");
                });

            modelBuilder.Entity("Mindflow_backend.Chat.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Mindflow_backend.Chat.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_chat_messages__conversations_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Mindflow_backend.Habits.Domain.Model.Entities.HabitCompletionLog", b =>
                {
                    b.HasOne("Mindflow_backend.Habits.Domain.Model.Aggregates.Habit", null)
                        .WithMany("CompletionLogs")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_habit_completion_logs_habits_habit_id");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.EntryTag", b =>
                {
                    b.HasOne("Mindflow_backend.Journal.Domain.Entities.JournalEntry", "Entry")
                        .WithMany("EntryTags")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_entry_tags__journal_entries_entry_id");

                    b.HasOne("Mindflow_backend.Journal.Domain.Entities.Tag", "Tag")
                        .WithMany("EntryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_entry_tags__tags_tag_id");

                    b.Navigation("Entry");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.JournalSearchToken", b =>
                {
                    b.HasOne("Mindflow_backend.Journal.Domain.Entities.JournalEntry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_journal_search_tokens_journal_entries_entry_id");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.Media", b =>
                {
                    b.HasOne("Mindflow_backend.Journal.Domain.Entities.JournalEntry", "Entry")
                        .WithMany("Media")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_media_journal_entries_entry_id");

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Mindflow_backend.Chat.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Mindflow_backend.Habits.Domain.Model.Aggregates.Habit", b =>
                {
                    b.Navigation("CompletionLogs");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.JournalEntry", b =>
                {
                    b.Navigation("EntryTags");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Mindflow_backend.Journal.Domain.Entities.Tag", b =>
                {
                    b.Navigation("EntryTags");
                });
#pragma warning restore 612, 618
        }
    }
}
