namespace Mindflow_backend.Journal.Application.Dtos;

/// <summary>
///     A single journal entry created/edited offline, submitted as part of a sync batch.
///     <see cref="ClientId" /> is generated by the client and is the stable identity for
///     this entry across sync retries (the client may not know the server-assigned Id yet).
/// </summary>
public class SyncJournalEntryItemRequest
{
    public string ClientId { get; set; } = string.Empty;
    public DateOnly Date { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
    public string Sentiment { get; set; } = "neutral";
    public string Category { get; set; } = "Sin categoría";

    /// <summary>
    ///     When the client last modified this entry locally (device clock). Used for
    ///     last-write-wins conflict resolution against the server's stored UpdatedAt.
    /// </summary>
    public DateTimeOffset ClientUpdatedAt { get; set; }

    /// <summary>
    ///     True if the client deleted this entry while offline.
    /// </summary>
    public bool Deleted { get; set; }
}
